workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.41    
    steps:
      - checkout      
      - run:
          name: "Run Hugo"          
          command: HUGO_ENV=production hugo -v -s /root/project/
      - run:
          name: "Test Website"
          command: htmlproofer /root/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    docker:
      - image: cibuilds/hugo:0.41
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Deployment
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              HUGO_ENV=production hugo -v -s /root/project/

              cp -a public/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi