workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.41
    working_directory: ~/project
    steps:
      - checkout
      - run: pwd
      - run:
          name: "Run Hugo"
          command: pwd
          #command: HUGO_ENV=production hugo -v -s hugo-blog/
      - run:
          name: "Test Website"
          command: htmlproofer hugo-blog/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
    deploy:
      steps:
        - run: echo "Just testing"